In [103]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [104]:
data_folder = '/content/drive/MyDrive/TrafficFlowPrediction'

In [105]:
data_file = f'{data_folder}/Scats Data October 2006.xls'

## Setup Environment

In [106]:
!pip install numpy==1.24.4 pandas==1.5.3 scikit-learn==1.3.1 xlrd

Requirement already satisfied: numpy==1.24.4 in /usr/local/lib/python3.11/dist-packages (1.24.4)
Requirement already satisfied: pandas==1.5.3 in /usr/local/lib/python3.11/dist-packages (1.5.3)
Requirement already satisfied: scikit-learn==1.3.1 in /usr/local/lib/python3.11/dist-packages (1.3.1)
Requirement already satisfied: xlrd in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.11/dist-packages (from pandas==1.5.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==1.5.3) (2025.2)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (1.15.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.1->pandas==1.5.3) (1.17.0)

In [107]:
import numpy as np
import pandas as pd
from typing import Sequence
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

## Utility

In [108]:
def read_excel(filename: str, sheet_name: str, header: int | Sequence[int]) -> pd.DataFrame:
    return pd.read_excel(filename, sheet_name=sheet_name, header=header)

# Scaling to [0-1] for RNN algos (LSTM, GRU, ...)
def scaler(x_min: float, x_max: float):
    return lambda x: (x - x_min) / (x_max - x_min)

# Rescaling scaled values to original
def rescaler(x_min: float, x_max: float):
    return lambda x: x * (x_max - x_min) + x_min

## Data Processing

In [109]:
df = read_excel(data_file, sheet_name="Data", header=1) # Read Excel data
df = df.sort_values(["NB_LATITUDE", "NB_LONGITUDE", "Date"]) # Sort by locations and date
df

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat,VR Internal Loc,NB_TYPE_SURVEY,Date,...,V86,V87,V88,V89,V90,V91,V92,V93,V94,V95
62,970,WARRIGAL_RD S of HIGH STREET_RD,060 G10,-37.8676,145.09146,10503,182,5,1,2006-10-01 00:15:00,...,95,117,87,82,55,58,57,51,41,41
63,970,WARRIGAL_RD S of HIGH STREET_RD,060 G10,-37.8676,145.09146,10503,182,5,1,2006-10-02 00:15:00,...,103,107,107,88,66,54,68,58,49,29
64,970,WARRIGAL_RD S of HIGH STREET_RD,060 G10,-37.8676,145.09146,10503,182,5,1,2006-10-03 00:15:00,...,131,144,100,100,102,86,85,68,53,37
65,970,WARRIGAL_RD S of HIGH STREET_RD,060 G10,-37.8676,145.09146,10503,182,5,1,2006-10-04 00:15:00,...,147,114,131,94,84,82,90,76,50,45
66,970,WARRIGAL_RD S of HIGH STREET_RD,060 G10,-37.8676,145.09146,10503,182,5,1,2006-10-05 00:15:00,...,185,158,127,118,92,105,113,78,64,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,4266,AUBURN_RD N of BURWOOD_RD,045 F11,0.0000,0.00000,4397,653,1,1,2006-10-27 00:15:00,...,77,52,58,55,68,55,62,62,64,42
3338,4266,AUBURN_RD N of BURWOOD_RD,045 F11,0.0000,0.00000,4397,653,1,1,2006-10-28 00:15:00,...,60,64,76,59,49,50,71,66,51,50
3339,4266,AUBURN_RD N of BURWOOD_RD,045 F11,0.0000,0.00000,4397,653,1,1,2006-10-29 00:15:00,...,79,85,63,62,58,56,54,45,35,22
3340,4266,AUBURN_RD N of BURWOOD_RD,045 F11,0.0000,0.00000,4397,653,1,1,2006-10-30 00:15:00,...,61,65,60,47,44,40,22,30,19,15
3341,4266,AUBURN_RD N of BURWOOD_RD,045 F11,0.0000,0.00000,4397,653,1,1,2006-10-31 00:15:00,...,77,46,79,65,68,38,34,28,26,22

### Grouping flows

In [110]:
lags = 7 # How many past flows data are used to predict the next flow

flow_columns = [f"V{str(i).zfill(2)}" for i in range(96)]  # Creates V00 to V95
scat_grouped = df.groupby(['NB_LATITUDE', 'NB_LONGITUDE'])[flow_columns].apply(lambda x: x.values.tolist())
scat_grouped

NB_LATITUDE  NB_LONGITUDE
-37.867600   145.091460      [[92, 93, 90, 55, 64, 50, 47, 36, 34, 36, 34, ...
-37.867350   145.091950      [[37, 30, 26, 29, 14, 20, 14, 10, 10, 8, 10, 7...
-37.867230   145.091030      [[47, 42, 31, 34, 40, 28, 27, 18, 11, 10, 15, ...
-37.867030   145.091590      [[86, 83, 52, 58, 59, 44, 31, 37, 30, 24, 16, ...
-37.861550   145.057510      [[66, 44, 40, 37, 34, 31, 31, 34, 19, 21, 22, ...
                                                   ...
-37.782670   145.077290      [[29, 29, 33, 25, 17, 22, 21, 14, 10, 11, 12, ...
-37.782087   145.077826      [[72, 57, 50, 43, 31, 37, 34, 24, 17, 23, 12, ...
-37.781270   145.076880      [[91, 97, 80, 87, 63, 50, 66, 60, 59, 52, 46, ...
-37.780930   145.077330      [[97, 92, 90, 57, 45, 54, 35, 29, 27, 36, 11, ...
 0.000000    0.000000        [[44, 53, 36, 35, 37, 25, 36, 26, 17, 21, 18, ...
Length: 140, dtype: object

### Scale lat/long

In [111]:
"""Scale lat/long"""
scat_latlong = np.array(scat_grouped.index.to_list())

# We would return those scalers in case we want to inverse transform it
lat_scaler = MinMaxScaler()
long_scaler = MinMaxScaler()

lats = scat_latlong[:, 0].reshape(-1, 1) # Get the lat column and reshaped it to 1D values
longs = scat_latlong[:, 1].reshape(-1, 1) # Get the long column and reshaped it to 1D values

lats_scaled = lat_scaler.fit_transform(lats) # Fit the scaler to the lats format and scale it to [0-1]
longs_scaled = long_scaler.fit_transform(longs) # Fit the scaler to the longs format and scale it to [0-1]

scat_latlong_scaled = np.hstack((lats_scaled, longs_scaled))
scat_latlong_scaled

array([[0.00000000e+00, 9.99949069e-01],
       [6.60194995e-06, 9.99952446e-01],
       [9.77088593e-06, 9.99946106e-01],
       [1.50524459e-05, 9.99949965e-01],
       [1.59767189e-04, 9.99715091e-01],
       [1.60559423e-04, 9.99721983e-01],
       [1.67237955e-04, 9.99718730e-01],
       [1.77460415e-04, 9.99714608e-01],
       [3.29305264e-04, 9.99964920e-01],
       [3.35643136e-04, 9.99967470e-01],
       [3.41452852e-04, 9.99965472e-01],
       [4.06416039e-04, 9.99968297e-01],
       [4.13810223e-04, 9.99970916e-01],
       [4.15394691e-04, 9.99967057e-01],
       [4.20340872e-04, 9.99968957e-01],
       [5.33173478e-04, 9.99681459e-01],
       [5.37134648e-04, 9.99684560e-01],
       [5.40303584e-04, 9.99677461e-01],
       [5.47697768e-04, 9.99629425e-01],
       [5.48490002e-04, 9.99682286e-01],
       [5.61957980e-04, 9.99620466e-01],
       [7.81934952e-04, 9.99985941e-01],
       [7.87744668e-04, 9.99740177e-01],
       [7.93290306e-04, 9.99736180e-01],
       [7.93554384e-04, 9.99990076e-01],
       [7.97251476e-04, 9.99982150e-01],
       [7.98043710e-04, 9.99740453e-01],
       [8.01476724e-04, 9.99736042e-01],
       [8.09399064e-04, 9.99987181e-01],
       [8.88886542e-04, 9.99748310e-01],
       [8.95224413e-04, 9.99751204e-01],
       [8.97337037e-04, 9.99746173e-01],
       [9.05523455e-04, 9.99749274e-01],
       [9.07636079e-04, 9.99699998e-01],
       [9.10540937e-04, 9.99702685e-01],
       [9.15294341e-04, 9.99704271e-01],
       [9.17935121e-04, 9.99698137e-01],
       [9.25329305e-04, 9.99700894e-01],
       [9.25857461e-04, 9.99698275e-01],
       [9.40381751e-04, 9.99638247e-01],
       [9.43814765e-04, 9.99640452e-01],
       [9.45399233e-04, 9.99636730e-01],
       [9.67845863e-04, 9.99544655e-01],
       [9.85010933e-04, 9.99548653e-01],
       [9.88972103e-04, 9.99539831e-01],
       [1.00587309e-03, 9.99546447e-01],
       [1.01617214e-03, 9.99427356e-01],
       [1.01854884e-03, 9.99419086e-01],
       [1.03016827e-03, 9.99432042e-01],
       [1.04469256e-03, 9.99998139e-01],
       [1.05155859e-03, 1.00000000e+00],
       [1.05314306e-03, 9.99996209e-01],
       [1.11388100e-03, 9.99618260e-01],
       [1.11572954e-03, 9.99858166e-01],
       [1.11731401e-03, 9.99621086e-01],
       [1.11784217e-03, 9.99853341e-01],
       [1.12021887e-03, 9.99615159e-01],
       [1.12338780e-03, 9.99856305e-01],
       [1.14055287e-03, 9.99552994e-01],
       [1.14715482e-03, 9.99556165e-01],
       [1.15005968e-03, 9.99549548e-01],
       [1.15032376e-03, 9.99762231e-01],
       [1.15428493e-03, 9.99553684e-01],
       [1.15692571e-03, 9.99764368e-01],
       [1.15824610e-03, 9.99760991e-01],
       [1.16990514e-03, 9.99491263e-01],
       [1.17382670e-03, 9.99713230e-01],
       [1.17435486e-03, 9.99495516e-01],
       [1.17910826e-03, 9.99484283e-01],
       [1.17910826e-03, 9.99716607e-01],
       [1.18184939e-03, 9.99491927e-01],
       [1.18201312e-03, 9.99710473e-01],
       [1.18729468e-03, 9.99713919e-01],
       [1.21607918e-03, 9.99422325e-01],
       [1.28025013e-03, 9.99718537e-01],
       [1.28870063e-03, 9.99714264e-01],
       [1.32461524e-03, 9.99723499e-01],
       [1.32922604e-03, 9.99720951e-01],
       [1.34098807e-03, 9.99994280e-01],
       [1.34811818e-03, 9.99996278e-01],
       [1.34996937e-03, 9.99992342e-01],
       [1.35445605e-03, 9.99994969e-01],
       [1.37716676e-03, 9.99501512e-01],
       [1.38350463e-03, 9.99505234e-01],
       [1.38640949e-03, 9.99498480e-01],
       [1.39037066e-03, 9.99469672e-01],
       [1.39195513e-03, 9.99502270e-01],
       [1.39538814e-03, 9.99869813e-01],
       [1.39723669e-03, 9.99474565e-01],
       [1.40040562e-03, 9.99467673e-01],
       [1.40463087e-03, 9.99473325e-01],
       [1.40489495e-03, 9.99873190e-01],
       [1.40779981e-03, 9.99866712e-01],
       [1.41440176e-03, 9.99870778e-01],
       [1.43869693e-03, 9.99376908e-01],
       [1.44292218e-03, 9.99375943e-01],
       [1.44371442e-03, 9.99378355e-01],
       [1.44582704e-03, 9.99377252e-01],
       [1.46404842e-03, 9.99727634e-01],
       [1.47012222e-03, 9.99731011e-01],
       [1.47249892e-03, 9.99725429e-01],
       [1.48226980e-03, 9.99728530e-01],
       [1.53305200e-03, 9.99572257e-01],
       [1.54026133e-03, 9.99575848e-01],
       [1.54063104e-03, 9.99506819e-01],
       [1.54284930e-03, 9.99569962e-01],
       [1.54960969e-03, 9.99505096e-01],
       [1.55093008e-03, 9.99511230e-01],
       [1.55383494e-03, 9.99508749e-01],
       [1.62038260e-03, 9.99561196e-01],
       [1.62170299e-03, 9.99562161e-01],
       [1.63622728e-03, 9.99881874e-01],
       [1.65101564e-03, 9.99887043e-01],
       [1.65656128e-03, 9.99876429e-01],
       [1.67134965e-03, 9.99883666e-01],
       [1.71756330e-03, 9.99740315e-01],
       [1.72284486e-03, 9.99743761e-01],
       [1.72574972e-03, 9.99737834e-01],
       [1.73182351e-03, 9.99741004e-01],
       [1.75649632e-03, 9.99654753e-01],
       [1.76245656e-03, 9.99660714e-01],
       [1.76467481e-03, 9.99659619e-01],
       [1.76853035e-03, 9.99653960e-01],
       [1.88155574e-03, 9.99894348e-01],
       [1.88604506e-03, 9.99892694e-01],
       [1.88789361e-03, 9.99895726e-01],
       [1.89951304e-03, 9.99739901e-01],
       [1.90109751e-03, 9.99749550e-01],
       [1.92248783e-03, 9.99526530e-01],
       [1.92328006e-03, 9.99530803e-01],
       [1.92486453e-03, 9.99740522e-01],
       [1.93859658e-03, 9.99798413e-01],
       [1.93886066e-03, 9.99798069e-01],
       [1.94202960e-03, 9.99793244e-01],
       [2.13876771e-03, 9.99746173e-01],
       [2.24281444e-03, 9.99851412e-01],
       [2.25820226e-03, 9.99855103e-01],
       [2.27978536e-03, 9.99848586e-01],
       [2.28876401e-03, 9.99851687e-01],
       [1.00000000e+00, 0.00000000e+00]])

### Scale flow & Flow window slicing

In [112]:
"""Scale flow"""
scat_data = scat_grouped.values

flow_max = np.array(scat_data.max()).max()
flow_min = np.array(scat_data.min()).min()

# We would return scaler and rescaler in case we want to scale and inverse scale it
flow_scaler = scaler(flow_min, flow_max) # Get the scaler of flow data
flow_rescaler = rescaler(flow_min, flow_max) # Get the rescaler of flow data

X_latlong = []
X_flow = []
y = []

for i, flow in enumerate(scat_grouped.values):
    flow = np.array(flow, dtype=float).flatten()
    flow = np.vectorize(flow_scaler)(flow)

    """Flow window slicing"""
    indices = np.arange(lags, len(flow))
    offset = np.arange(-lags, 0)

    for idx in indices:
        past_flow = flow[idx + offset]  # past lags
        target = flow[idx]              # current target
        X_flow.append(past_flow)
        X_latlong.append(scat_latlong_scaled[i])
        y.append(target)

### Split training/test data

In [113]:
# Convert lists to numpy arrays
X_latlong = np.array(X_latlong)
X_flow = np.array(X_flow)
y = np.array(y)

# Combine into a single X tuple for train/test split
combined_X = list(zip(X_latlong, X_flow))

# Perform train-test split
X_train_comb, X_test_comb, y_train, y_test = train_test_split(combined_X, y, random_state=0, train_size=0.75)

# Unzip the combined tuples back into separate arrays
X_latlong_train, X_flow_train = zip(*X_train_comb)
X_latlong_test, X_flow_test = zip(*X_test_comb)

# Convert back to np.ndarray
X_latlong_train = np.array(X_latlong_train)
X_flow_train = np.array(X_flow_train)
X_latlong_test = np.array(X_latlong_test)
X_flow_test = np.array(X_flow_test)

In [114]:
X_latlong_train

array([[1.12021887e-03, 9.99615159e-01],
       [1.15428493e-03, 9.99553684e-01],
       [1.11784217e-03, 9.99853341e-01],
       ...,
       [1.11388100e-03, 9.99618260e-01],
       [9.43814765e-04, 9.99640452e-01],
       [1.55093008e-03, 9.99511230e-01]])

In [115]:
X_flow_train

array([[0.21698113, 0.25943396, 0.22484277],
       [0.21069182, 0.22012579, 0.22012579],
       [0.27672956, 0.28616352, 0.25471698],
       ...,
       [0.06603774, 0.0581761 , 0.11477987],
       [0.09748428, 0.10220126, 0.11163522],
       [0.10849057, 0.13522013, 0.13679245]])

In [116]:
y_train

array([0.25786164, 0.20440252, 0.22169811, ..., 0.14308176, 0.10849057,
       0.10534591])

In [117]:
X_latlong_test

array([[3.41452852e-04, 9.99965472e-01],
       [7.97251476e-04, 9.99982150e-01],
       [1.15428493e-03, 9.99553684e-01],
       ...,
       [1.17435486e-03, 9.99495516e-01],
       [1.38640949e-03, 9.99498480e-01],
       [1.50524459e-05, 9.99949965e-01]])

In [118]:
X_flow_test

array([[0.02044025, 0.01886792, 0.01886792],
       [0.30503145, 0.28459119, 0.18710692],
       [0.05503145, 0.04716981, 0.03773585],
       ...,
       [0.10062893, 0.1163522 , 0.08962264],
       [0.15251572, 0.16037736, 0.16981132],
       [0.43710692, 0.37264151, 0.38522013]])

In [119]:
y_test

array([0.02515723, 0.17295597, 0.06132075, ..., 0.07232704, 0.16037736,
       0.32389937])